# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20161106_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(help_text='The title of this link', max_length=200, null=True, verbose_name='Link Title'),
        ),
    ]
