# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    def generate_titles(apps, schema_editor):
        Links = apps.get_model('links', 'Link')

        # Get all links that don't have titles.
        no_titles = Links.objects.filter(title=None)

        # Generate a default title.
        for link in no_titles:
            title = 'Link - {}'.format(link.key)
            link.title = title
            link.save()

    dependencies = [
        ('links', '0003_link_title'),
    ]

    operations = [
        migrations.RunPython(generate_titles),
    ]
