# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_link_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of tag', max_length=80, verbose_name='Tag Name')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(help_text="The tags of the link", related_name='links', to='links.Tag', verbose_name='Link Tags'),
        ),
    ]
