# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20161115_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, help_text='The title of this link', max_length=200, verbose_name='Link Title'),
        ),
    ]
