# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_title_blank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='total_clicks',
        ),
    ]
