# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0005_auto_20161115_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='links.Link', verbose_name='Link')),
            ],
        ),
    ]
