# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_ipaddress_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text='The referer for the link', max_length=80, verbose_name='Referer source')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='The total clicks from this referer', verbose_name='Total referer clicks')),
                ('last_visited', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.ForeignKey(help_text="A link's referer", on_delete=django.db.models.deletion.CASCADE, related_name='referers', to='links.Link', verbose_name='Link')),
            ],
        ),
    ]
