# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_country_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='analytics.Country', verbose_name='Country'),
        ),
    ]
